### ISSUE TITLE
add feature: add -e,--external to f2 predict

### ISSUE THREAD

**Issue by nextgenusfs** [nextgenusfs/funannotate2#3]
Should be able to pass in externally derived GFF3 gene model predictions, ie from newer AI/DL/ML methods like helixer and/or Tiberius.  But the requirements are too onerous to include as a dependency.  Idea is that GFF3 can be passed via CLI, use `gfftk sanitize` to clean up the input and then add to predictions pool.

**Comment by hyphaltip** [comment]
If we do a nextflow style workflow assume that could run these separately
and pass in. Better to keep the core lightweight as you have done!

Sent from Gmail Mobile

Jason Stajich - ***@***.***

**Comment by nextgenusfs** [comment]
Yeah needs to be as dependency-light as we can make it. I'm leaning towards not building in external tools for parsers/etc for `f2 annotate` as well, it's too hard to keep updating when tools change. Instead, just allow for the 3 column TSV format to add any annotation of choosing. I've kept in some of the basics (pfam, cazy, merops, uniprot, busco) -- but not going to do emapper, interpro, signalp, antismash, etc.

**Comment by nextgenusfs** [comment]
completed
